In [23]:
import pandas as pd

In [24]:
df=pd.read_csv("Dataset/ML Intern Dataset.csv")

In [25]:
df.head()

,SN,Train_No,Station_Code,1A,2A,3A,SL,Station_Name,Route_Number,Arrival_time,Departure_Time,Distance
0,1,107,SWV,100,100,100,100,SAWANTWADI R,1,00:00:00,10:25:00,0
1,2,107,THVM,260,228,196,164,THIVIM,1,11:06:00,11:08:00,32
2,3,107,KRMI,345,296,247,198,KARMALI,1,11:28:00,11:30:00,49
3,4,107,MAO,490,412,334,256,MADGOAN JN.,1,12:10:00,00:00:00,78
4,1,108,MAO,100,100,100,100,MADGOAN JN.,1,00:00:00,20:30:00,0

In [26]:
df.shape

(186074, 12)

In [27]:
df.columns

Index(['SN', 'Train_No', 'Station_Code', '1A', '2A', '3A', 'SL',
       'Station_Name', 'Route_Number', 'Arrival_time', 'Departure_Time',
       'Distance'],
      dtype='object')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186074 entries, 0 to 186073
Data columns (total 12 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   SN              186074 non-null  int64
 1   Train_No        186074 non-null  int64
 2   Station_Code    186074 non-null  object
 3   1A              186074 non-null  int64
 4   2A              186074 non-null  int64
 5   3A              186074 non-null  int64
 6   SL              186074 non-null  int64
 7   Station_Name    186074 non-null  object
 8   Route_Number    186074 non-null  int64
 9   Arrival_time    186074 non-null  object
 10  Departure_Time  186074 non-null  object
 11  Distance        186074 non-null  int64
dtypes: int64(8), object(4)
memory usage: 17.0+ MB

In [ ]:
df.describe()

<bound method NDFrame.describe of         SN  Train_No Station_Code    1A    2A    3A    SL     Station_Name  \
0        1       107          SWV   100   100   100   100     SAWANTWADI R
1        2       107         THVM   260   228   196   164           THIVIM
2        3       107         KRMI   345   296   247   198          KARMALI
3        4       107          MAO   490   412   334   256      MADGOAN JN.
4        1       108          MAO   100   100   100   100      MADGOAN JN.
...     ..       ...          ...   ...   ...   ...   ...              ...
186069   1     22439         NDLS   100   100   100   100        NEW DELHI
186070   2     22439          UMB  1095   896   697  1095   AMBALA CANT JN
186071   3     22439          LDH  1660  1348  1036  1660      LUDHIANA JN
186072   4     22439          JAT  2985  2408  1831  2985       JAMMU TAWI
186073   5     22439         SVDK  3375  2720  2065  3375  SHMATA VD KATRA

        Route_Number Arrival_time Departure_Time  Distance
0                  1     00:00:00       10:25:00         0
1                  1     11:06:00       11:08:00        32
2                  1     11:28:00       11:30:00        49
3                  1     12:10:00       00:00:00        78
4                  1     00:00:00       20:30:00         0
...              ...          ...            ...       ...
186069             1     00:00:00       06:00:00         0
186070             1     08:08:00       08:10:00       199
186071             1     09:19:00       09:21:00       312
186072             1     12:38:00       12:40:00       577
186073             1     14:00:00       00:00:00       655

[186074 rows x 12 columns]>

In [30]:
df["Train_No"].nunique()

11113

In [31]:
df.isnull().sum()

SN                0
Train_No          0
Station_Code      0
1A                0
2A                0
3A                0
SL                0
Station_Name      0
Route_Number      0
Arrival_time      0
Departure_Time    0
Distance          0
dtype: int64

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df_sorted=df.sort_values(["Train_No", "Route_Number"])

In [34]:
train_stations = df_sorted.groupby("Train_No").agg(
    Starting_Station=("Station_Name", "first"),
    Ending_Station=("Station_Name", "last")
).reset_index()

train_stations.head()

   Train_No Starting_Station Ending_Station
0       107     SAWANTWADI R    MADGOAN JN.
1       108      MADGOAN JN.   SAWANTWADI R
2       128      MADGOAN JN.    CHHATRAPATI
3       290     DELHI-SAFDAR   DELHI-SAFDAR
4       401       AURANGABAD   VARANASI JN.

In [35]:
train_distance= df_sorted.groupby("Train_No")["Distance"].max()
train_distance.head()

Train_No
107      78
108      83
128     978
290    2694
401    1618
Name: Distance, dtype: int64

In [36]:
train_stops=df_sorted.groupby("Train_No").size()
train_stops.head()

Train_No
107     4
108     4
128    22
290    14
401    12
dtype: int64

In [37]:
train_distance.describe()

count    11113.000000
mean       348.870242
std        596.179751
min          1.000000
25%         38.000000
50%         82.000000
75%        324.000000
max       4260.000000
Name: Distance, dtype: float64

In [38]:
train_stops.describe()

count    11113.000000
mean        16.743814
std         12.993123
min          2.000000
25%          8.000000
50%         15.000000
75%         22.000000
max        118.000000
dtype: float64